name: Renovate

on:
  schedule:
    - cron: '0 4 * * 1' # Every Monday at 4am UTC
  workflow_dispatch:

permissions: {}

jobs:
  renovate:
    name: Renovate
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: read
    steps:
      - name: Harden runner
        uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # v2.21.0
        with:
          egress-policy: audit

      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          persist-credentials: false

      - name: Get token
        id: get_token
        uses: actions/create-github-app-token@fee1f7d63c2ff003460e3d139729b119787bc349 # v2.2.2
        with:
          app-id: ${{ secrets.RENOVATE_APP_ID }}
          private-key: ${{ secrets.RENOVATE_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - uses: renovatebot/github-action@e09d604f8f803bb527bd8321ed5be06c460b8682 # v46.2.2
        with:
          configurationFile: .github/renovate-config.json
          token: '${{ steps.get_token.outputs.token }}'
        env:
          RENOVATE_PLATFORM_COMMIT: 'enabled'
